### ISSUE TITLE
main_inception_v4.py line285 nonlocal？

### ISSUE THREAD

**Issue by fengdongsheng** [Herbert95/tianchi_lvcai#1]
nonlocal lr 
报错：SyntaxError: invalid syntax

**Comment by herbert-chen** [comment]
你好，如果你去掉了main函数，改成了直接运行，那么需要把nonlocal关键词改成global

**Comment by fengdongsheng** [comment]
3q ,i changed it to global;
还有一个地方可能报错：
line:os.environ["CUDA_VISIBLE_DEVICES"] = '0,1'，
先看看还有哪些卡是空的，我的两张卡，只有卡1空着，so:os.environ["CUDA_VISIBLE_DEVICES"] = '1'
