### ISSUE TITLE
报错 ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by FelixZhang7** [Herbert95/tianchi_lvcai#2]
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by herbert-chen** [comment]
不知道是哪一行报错了？有完整的错误信息吗？
可能是DataFrame有缺失值，或者有除0错误。

**Comment by FelixZhang7** [comment]
@Herbert95 好的谢谢！请问有什么优化调参上的提示吗
