### ISSUE TITLE
有没有数据分享一下呢？

### ISSUE THREAD

**Issue by StevenLOL** [Herbert95/tianchi_lvcai#3]
有没有数据分享一下呢？

**Comment by nico-zck** [comment]
+1

**Comment by ZengYouxuan** [comment]
+1

**Comment by herbert-chen** [comment]
https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA，提取码：w7tn
别人的分享，仅供参考

**Comment by xvrong** [comment]
https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA
提取码：w7tn

这个链接是对的，但是格式有些问题。
> [https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA，提取码：w7tn](https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9Aw7tn) 别人的分享，仅供参考
